import "./globals.css";
import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import Navbar from "@/components/ui/navbar";

const inter = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
